//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.SampleV5toV6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hardware.
    /// </summary>
    // *** Start programmer edit section *** (Hardware CustomAttributes)

    // *** End programmer edit section *** (Hardware CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'",
            "SerialNumber as \'Serial number\'"})]
    [View("HardwareE", new string[] {
            "Name as \'Name\'",
            "SerialNumber as \'Serial number\'"})]
    public class Hardware : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private string fSerialNumber;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.SampleV5toV6.Notebook fNotebook;
        
        // *** Start programmer edit section *** (Hardware CustomMembers)

        // *** End programmer edit section *** (Hardware CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Name CustomAttributes)

        // *** End programmer edit section *** (Hardware.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Name Get start)

                // *** End programmer edit section *** (Hardware.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Hardware.Name Get end)

                // *** End programmer edit section *** (Hardware.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Name Set start)

                // *** End programmer edit section *** (Hardware.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Hardware.Name Set end)

                // *** End programmer edit section *** (Hardware.Name Set end)
            }
        }
        
        /// <summary>
        /// SerialNumber.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.SerialNumber CustomAttributes)

        // *** End programmer edit section *** (Hardware.SerialNumber CustomAttributes)
        [StrLen(255)]
        public virtual string SerialNumber
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.SerialNumber Get start)

                // *** End programmer edit section *** (Hardware.SerialNumber Get start)
                string result = this.fSerialNumber;
                // *** Start programmer edit section *** (Hardware.SerialNumber Get end)

                // *** End programmer edit section *** (Hardware.SerialNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.SerialNumber Set start)

                // *** End programmer edit section *** (Hardware.SerialNumber Set start)
                this.fSerialNumber = value;
                // *** Start programmer edit section *** (Hardware.SerialNumber Set end)

                // *** End programmer edit section *** (Hardware.SerialNumber Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Hardware.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.CreateTime Get start)

                // *** End programmer edit section *** (Hardware.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Hardware.CreateTime Get end)

                // *** End programmer edit section *** (Hardware.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.CreateTime Set start)

                // *** End programmer edit section *** (Hardware.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Hardware.CreateTime Set end)

                // *** End programmer edit section *** (Hardware.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Creator CustomAttributes)

        // *** End programmer edit section *** (Hardware.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Creator Get start)

                // *** End programmer edit section *** (Hardware.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Hardware.Creator Get end)

                // *** End programmer edit section *** (Hardware.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Creator Set start)

                // *** End programmer edit section *** (Hardware.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Hardware.Creator Set end)

                // *** End programmer edit section *** (Hardware.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.EditTime CustomAttributes)

        // *** End programmer edit section *** (Hardware.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.EditTime Get start)

                // *** End programmer edit section *** (Hardware.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Hardware.EditTime Get end)

                // *** End programmer edit section *** (Hardware.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.EditTime Set start)

                // *** End programmer edit section *** (Hardware.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Hardware.EditTime Set end)

                // *** End programmer edit section *** (Hardware.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Editor CustomAttributes)

        // *** End programmer edit section *** (Hardware.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Editor Get start)

                // *** End programmer edit section *** (Hardware.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Hardware.Editor Get end)

                // *** End programmer edit section *** (Hardware.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Editor Set start)

                // *** End programmer edit section *** (Hardware.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Hardware.Editor Set end)

                // *** End programmer edit section *** (Hardware.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.SampleV5toV6.Notebook.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Notebook CustomAttributes)

        // *** End programmer edit section *** (Hardware.Notebook CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Notebook"})]
        public virtual NewPlatform.SampleV5toV6.Notebook Notebook
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Notebook Get start)

                // *** End programmer edit section *** (Hardware.Notebook Get start)
                NewPlatform.SampleV5toV6.Notebook result = this.fNotebook;
                // *** Start programmer edit section *** (Hardware.Notebook Get end)

                // *** End programmer edit section *** (Hardware.Notebook Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Notebook Set start)

                // *** End programmer edit section *** (Hardware.Notebook Set start)
                this.fNotebook = value;
                // *** Start programmer edit section *** (Hardware.Notebook Set end)

                // *** End programmer edit section *** (Hardware.Notebook Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.SampleV5toV6.Hardware));
                }
            }
            
            /// <summary>
            /// "HardwareE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareE", typeof(NewPlatform.SampleV5toV6.Hardware));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of Hardware.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)
    public class DetailArrayOfHardware : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.SampleV5toV6.DetailArrayOfHardware members)

        // *** End programmer edit section *** (NewPlatform.SampleV5toV6.DetailArrayOfHardware members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Hardware by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Hardware.
        /// </summary>
        public DetailArrayOfHardware(NewPlatform.SampleV5toV6.Notebook fNotebook) : 
                base(typeof(Hardware), ((ICSSoft.STORMNET.DataObject)(fNotebook)))
        {
        }
        
        public NewPlatform.SampleV5toV6.Hardware this[int index]
        {
            get
            {
                return ((NewPlatform.SampleV5toV6.Hardware)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.SampleV5toV6.Hardware dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
