//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("SampleV5toV6")]
[assembly: System.Reflection.AssemblyDescription("SampleV5toV6")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("NewPlatform")]
[assembly: System.Reflection.AssemblyProduct("SampleV5toV6")]
[assembly: System.Reflection.AssemblyCopyright("2021")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.1")]

